name: "HTMLProofer"
author: "chabad360"
description: "Test your rendered HTML files to make sure they're accurate."

inputs:
  directory:
    description: "The directory to scan"
    required: true
  arguments:
      description: "HTMLProofer options"
      required: false
  output_file:
      description: "Specify this if you want the output to be generated into a file. For later use."
      required: false
      default: "htmlproofer_results.txt"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check"
  color: "green"
